# Generated by Django 6.0.3 on 2026-03-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bloqueado_hasta_customuser_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='training_goal',
            field=models.CharField(blank=True, choices=[('hypertrophy', 'Hipertrofia'), ('fat_loss', 'Pérdida grasa'), ('endurance', 'Resistencia'), ('maintenance', 'Mantenimiento')], max_length=20, null=True),
        ),
    ]
