# Generated by Django 6.0.3 on 2026-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Si es plantilla para usar con múltiples usuarios'),
        ),
    ]
