# Generated by Django 6.0.3 on 2026-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_exercisecompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise_gifs/', verbose_name='GIF explicativo'),
        ),
    ]
