# Generated by Django 6.0.3 on 2026-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_exercise_image_url_remove_exercise_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la rutina', null=True),
        ),
    ]
