# Generated by Django 6.0.3 on 2026-05-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_routine_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinedetail',
            name='suggested_weight',
            field=models.FloatField(blank=True, help_text='Peso sugerido en kg', null=True),
        ),
    ]
