# Generated by Django 6.0.3 on 2026-05-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_routinedetail_suggested_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='reps_performed',
            field=models.JSONField(blank=True, default=dict, help_text='Repeticiones realizadas por ejercicio, ej: {exercise_id: 12}'),
        ),
    ]
