# Generated by Django 6.0.3 on 2026-06-01 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_correctionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='correctionlog',
            name='angles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionlog',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='correctionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='reps_performed',
            field=models.JSONField(blank=True, default=dict, help_text='Repeticiones realizadas por ejercicio'),
        ),
    ]
